// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IAddUrlRequest {
    name?: string;
    url?: string;
}

export default class AddUrlRequest {
    readonly _name: string | undefined;

    get name(): string | undefined {
        return this._name;
    }

    readonly _url: string | undefined;

    /**
     * Description: URL or an absolute path to the file containing filtering rules
     * Example: https://filters.adtidy.org/windows/filters/15.txt
     */
    get url(): string | undefined {
        return this._url;
    }

    constructor(props: IAddUrlRequest) {
        if (typeof props.name === 'string') {
            this._name = props.name.trim();
        }
        if (typeof props.url === 'string') {
            this._url = props.url.trim();
        }
    }

    serialize(): IAddUrlRequest {
        const data: IAddUrlRequest = {
        };
        if (typeof this._name !== 'undefined') {
            data.name = this._name;
        }
        if (typeof this._url !== 'undefined') {
            data.url = this._url;
        }
        return data;
    }

    validate(): string[] {
        const validateRequired = {
            name: !this._name ? true : typeof this._name === 'string' && !this._name ? true : this._name,
            url: !this._url ? true : typeof this._url === 'string' && !this._url ? true : this._url,
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IAddUrlRequest): AddUrlRequest {
        return new AddUrlRequest(props);
    }

    readonly keys: { [key: string]: string } = {
        name: 'name',
        url: 'url',
        }
;

    mergeDeepWith(props: Partial<AddUrlRequest>): AddUrlRequest {
        const updateData: Partial<IAddUrlRequest> = {};
        Object.keys(props).forEach((key: keyof AddUrlRequest) => {
            const updateKey = this.keys[key] as keyof IAddUrlRequest;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IAddUrlRequest, keyof IAddUrlRequest>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new AddUrlRequest({ ...this.serialize(), ...updateData });
    }
}
