// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IBlockedServicesArray {
}

export default class BlockedServicesArray {
    constructor(props: IBlockedServicesArray) {
    }

    serialize(): IBlockedServicesArray {
        const data: IBlockedServicesArray = {
        };
        return data;
    }

    validate(): string[] {
        const validateRequired = {
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IBlockedServicesArray): BlockedServicesArray {
        return new BlockedServicesArray(props);
    }

    readonly keys: { [key: string]: string } = {
        }
;

    mergeDeepWith(props: Partial<BlockedServicesArray>): BlockedServicesArray {
        const updateData: Partial<IBlockedServicesArray> = {};
        Object.keys(props).forEach((key: keyof BlockedServicesArray) => {
            const updateKey = this.keys[key] as keyof IBlockedServicesArray;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IBlockedServicesArray, keyof IBlockedServicesArray>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new BlockedServicesArray({ ...this.serialize(), ...updateData });
    }
}
