// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IClientsFindResponse {
}

export default class ClientsFindResponse {
    constructor(props: IClientsFindResponse) {
    }

    serialize(): IClientsFindResponse {
        const data: IClientsFindResponse = {
        };
        return data;
    }

    validate(): string[] {
        const validateRequired = {
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IClientsFindResponse): ClientsFindResponse {
        return new ClientsFindResponse(props);
    }

    readonly keys: { [key: string]: string } = {
        }
;

    mergeDeepWith(props: Partial<ClientsFindResponse>): ClientsFindResponse {
        const updateData: Partial<IClientsFindResponse> = {};
        Object.keys(props).forEach((key: keyof ClientsFindResponse) => {
            const updateKey = this.keys[key] as keyof IClientsFindResponse;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IClientsFindResponse, keyof IClientsFindResponse>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new ClientsFindResponse({ ...this.serialize(), ...updateData });
    }
}
