// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IClientsArray {
}

export default class ClientsArray {
    constructor(props: IClientsArray) {
    }

    serialize(): IClientsArray {
        const data: IClientsArray = {
        };
        return data;
    }

    validate(): string[] {
        const validateRequired = {
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IClientsArray): ClientsArray {
        return new ClientsArray(props);
    }

    readonly keys: { [key: string]: string } = {
        }
;

    mergeDeepWith(props: Partial<ClientsArray>): ClientsArray {
        const updateData: Partial<IClientsArray> = {};
        Object.keys(props).forEach((key: keyof ClientsArray) => {
            const updateKey = this.keys[key] as keyof IClientsArray;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IClientsArray, keyof IClientsArray>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new ClientsArray({ ...this.serialize(), ...updateData });
    }
}
