// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IClientDelete {
    name?: string;
}

export default class ClientDelete {
    readonly _name: string | undefined;

    get name(): string | undefined {
        return this._name;
    }

    constructor(props: IClientDelete) {
        if (typeof props.name === 'string') {
            this._name = props.name.trim();
        }
    }

    serialize(): IClientDelete {
        const data: IClientDelete = {
        };
        if (typeof this._name !== 'undefined') {
            data.name = this._name;
        }
        return data;
    }

    validate(): string[] {
        const validateRequired = {
            name: !this._name ? true : typeof this._name === 'string' && !this._name ? true : this._name,
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IClientDelete): ClientDelete {
        return new ClientDelete(props);
    }

    readonly keys: { [key: string]: string } = {
        name: 'name',
        }
;

    mergeDeepWith(props: Partial<ClientDelete>): ClientDelete {
        const updateData: Partial<IClientDelete> = {};
        Object.keys(props).forEach((key: keyof ClientDelete) => {
            const updateKey = this.keys[key] as keyof IClientDelete;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IClientDelete, keyof IClientDelete>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new ClientDelete({ ...this.serialize(), ...updateData });
    }
}
