// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IDhcpSearchResultStaticIP {
    ip?: string;
    static?: string;
}

export default class DhcpSearchResultStaticIP {
    readonly _ip: string | undefined;

    /** */
    get ip(): string | undefined {
        return this._ip;
    }

    readonly _static: string | undefined;

    /**
     * Description: yes|no|error
     * Example: yes
     */
    get static(): string | undefined {
        return this._static;
    }

    constructor(props: IDhcpSearchResultStaticIP) {
        if (typeof props.ip === 'string') {
            this._ip = props.ip.trim();
        }
        if (typeof props.static === 'string') {
            this._static = props.static.trim();
        }
    }

    serialize(): IDhcpSearchResultStaticIP {
        const data: IDhcpSearchResultStaticIP = {
        };
        if (typeof this._ip !== 'undefined') {
            data.ip = this._ip;
        }
        if (typeof this._static !== 'undefined') {
            data.static = this._static;
        }
        return data;
    }

    validate(): string[] {
        const validateRequired = {
            static: !this._static ? true : typeof this._static === 'string' && !this._static ? true : this._static,
            ip: !this._ip ? true : typeof this._ip === 'string' && !this._ip ? true : this._ip,
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IDhcpSearchResultStaticIP): DhcpSearchResultStaticIP {
        return new DhcpSearchResultStaticIP(props);
    }

    readonly keys: { [key: string]: string } = {
        ip: 'ip',
        static: 'static',
        }
;

    mergeDeepWith(props: Partial<DhcpSearchResultStaticIP>): DhcpSearchResultStaticIP {
        const updateData: Partial<IDhcpSearchResultStaticIP> = {};
        Object.keys(props).forEach((key: keyof DhcpSearchResultStaticIP) => {
            const updateKey = this.keys[key] as keyof IDhcpSearchResultStaticIP;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IDhcpSearchResultStaticIP, keyof IDhcpSearchResultStaticIP>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new DhcpSearchResultStaticIP({ ...this.serialize(), ...updateData });
    }
}
