// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IRewriteList {
}

export default class RewriteList {
    constructor(props: IRewriteList) {
    }

    serialize(): IRewriteList {
        const data: IRewriteList = {
        };
        return data;
    }

    validate(): string[] {
        const validateRequired = {
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IRewriteList): RewriteList {
        return new RewriteList(props);
    }

    readonly keys: { [key: string]: string } = {
        }
;

    mergeDeepWith(props: Partial<RewriteList>): RewriteList {
        const updateData: Partial<IRewriteList> = {};
        Object.keys(props).forEach((key: keyof RewriteList) => {
            const updateKey = this.keys[key] as keyof IRewriteList;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IRewriteList, keyof IRewriteList>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new RewriteList({ ...this.serialize(), ...updateData });
    }
}
