// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IWhoisInfo {
    key?: string;
}

export default class WhoisInfo {
    readonly _key: string | undefined;

    get key(): string | undefined {
        return this._key;
    }

    constructor(props: IWhoisInfo) {
        if (typeof props.key === 'string') {
            this._key = props.key.trim();
        }
    }

    serialize(): IWhoisInfo {
        const data: IWhoisInfo = {
        };
        if (typeof this._key !== 'undefined') {
            data.key = this._key;
        }
        return data;
    }

    validate(): string[] {
        const validateRequired = {
            key: !this._key ? true : typeof this._key === 'string' && !this._key ? true : this._key,
        };
        const isError: string[] = [];
        Object.keys(validateRequired).forEach((key) => {
            if (!(validateRequired as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: IWhoisInfo): WhoisInfo {
        return new WhoisInfo(props);
    }

    readonly keys: { [key: string]: string } = {
        key: 'key',
        }
;

    mergeDeepWith(props: Partial<WhoisInfo>): WhoisInfo {
        const updateData: Partial<IWhoisInfo> = {};
        Object.keys(props).forEach((key: keyof WhoisInfo) => {
            const updateKey = this.keys[key] as keyof IWhoisInfo;
            if ((props[key] as any).serialize) {
                (updateData[updateKey] as any) = (props[key] as any).serialize() as Pick<IWhoisInfo, keyof IWhoisInfo>;
            } else {
                (updateData[updateKey] as any) = props[key];
            }
        });
        return new WhoisInfo({ ...this.serialize(), ...updateData });
    }
}
