import AddressesInfo, { IAddressesInfo } from 'Entities/AddressesInfo';
import CheckConfigRequest, { ICheckConfigRequest } from 'Entities/CheckConfigRequest';
import CheckConfigResponse, { ICheckConfigResponse } from 'Entities/CheckConfigResponse';
import InitialConfiguration, { IInitialConfiguration } from 'Entities/InitialConfiguration';

// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export default class InstallApi {
    static async installCheckConfig(checkconfigrequest: ICheckConfigRequest): Promise<ICheckConfigResponse | string[] | Error> {
        const haveError: string[] = [];
        const checkconfigrequestValid = new CheckConfigRequest(checkconfigrequest);
        haveError.push(...checkconfigrequestValid.validate());
        if (haveError.length > 0) {
            return Promise.resolve(haveError);
        }
        return await fetch(`/install/check_config`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(checkconfigrequestValid.serialize()),
        }).then(async (res) => {
            if (res.status === 200) {
                return res.json();
            } else {
                return new Error(String(res.status));
            }
        })
    }

    static async installConfigure(initialconfiguration: IInitialConfiguration): Promise<number | string[] | Error> {
        const haveError: string[] = [];
        const initialconfigurationValid = new InitialConfiguration(initialconfiguration);
        haveError.push(...initialconfigurationValid.validate());
        if (haveError.length > 0) {
            return Promise.resolve(haveError);
        }
        return await fetch(`/install/configure`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(initialconfigurationValid.serialize()),
        }).then(async (res) => {
            if (res.status === 200) {
                return res.status;
            } else {
                return new Error(String(res.status));
            }
        })
    }

    static async installGetAddresses(): Promise<IAddressesInfo | Error> {
        return await fetch(`/install/get_addresses`, {
            method: 'GET',
        }).then(async (res) => {
            if (res.status === 200) {
                return res.json();
            } else {
                return new Error(String(res.status));
            }
        })
    }
}
